---
  Resources:
    cfMyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref vpccidrblock     # required-make it as parameter
        EnableDnsHostnames: true     # optional
        EnableDnsSupport: true     # optional
        InstanceTenancy: default     # optional
        Tags:                # optional, list of Tag
          - Key: Name
            Value: GreatVPC
    vpccidrblock_name:
      Type: AWS::EC2::VPCCidrBlock
      Properties:
        VpcId: !Ref  cfMyVPC    # required
  Parameters:
    vpccidrblock:
      Type: Number      # Required, one of: String, Number, List<Number>, CommaDelimitedList
            # OR
            # AWS::EC2::AvailabilityZone::Name
            # AWS::EC2::Image::Id
            # AWS::EC2::Instance::Id
            # AWS::EC2::KeyPair::KeyName
            # AWS::EC2::SecurityGroup::GroupName
            # AWS::EC2::SecurityGroup::Id
            # AWS::EC2::Subnet::Id
            # AWS::EC2::Volume::Id
            # AWS::EC2::VPC::Id
            # AWS::Route53::HostedZone::Id
            # OR List<AWS-Type>
      Description: Input a valid CIDR Block in slah Notation    # optional, string, description of parameter value
      Default: 172.31.0.0/16    # optional
