---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MYCidrBlock:
      Description: IPv4 CidrBlock like 10.0.0.0/16
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 10.0.0.0/16
      AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
      ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VPCSubnetIpBlocks:
    Description: "Comma-delimited list of three CIDR blocks"
    Type: CommaDelimitedList
    Default: "10.0.1.0/24, 10.0.2.0/24, 10.0.3.0/24, 10.0.4.0/24"
  AZonePublic:
    Description: Please select two AvailabilityZone to create a Publicsubnets
    Type: List<AWS::EC2::AvailabilityZone::Name>
  AZonePrivate:
    Description: Please select two AvailabilityZone to create a Privatesubnets
    Type: List<AWS::EC2::AvailabilityZone::Name>
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MYCidrBlock     # define in parameter
      EnableDnsHostnames: True     # optional
      EnableDnsSupport: True     # optional
      InstanceTenancy: default     # optional
      Tags:                # optional, list of Tag
        - Key: Name
          Value: CFProject
  DMZ1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !Ref AZonePublic ]      # optional
      CidrBlock: !Select [0, !Ref VPCSubnetIpBlocks]    # required
      MapPublicIpOnLaunch: True     # optional
      Tags:                # optional, list of Tag
        - Key: Name
          Value: PublicSub-1a
      VpcId: !Ref MyVPC     # required
  DMZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !Ref AZonePublic ]     # optional
      CidrBlock: !Select [1, !Ref VPCSubnetIpBlocks]    # required
      MapPublicIpOnLaunch: True     # optional
      Tags:                # optional, list of Tag
        - Key: Name
          Value: PublicSub-1b
      VpcId: !Ref MyVPC     # Required
  PRV1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !Ref AZonePrivate ]     # optional
      CidrBlock: !Select [2, !Ref VPCSubnetIpBlocks]    # required
      MapPublicIpOnLaunch: False     # optional
      Tags:                # optional, list of Tag
        - Key: Name
          Value: PrivateSub-1a
      VpcId: !Ref MyVPC     # required
  PRV2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !Ref AZonePrivate ]     # optional
      CidrBlock: !Select [3, !Ref VPCSubnetIpBlocks]    # required
      MapPublicIpOnLaunch: False     # optional
      Tags:                # optional, list of Tag
        - Key: Name
          Value: PrivateSub-1b
      VpcId: !Ref MyVPC     # required
  MyIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: CFProject
  VPCandIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyIGW     # optional
      VpcId: !Ref MyVPC     # required
  PublicRT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PubRT
  PrivateRT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrvRT
  ToInternet:
    Type: 'AWS::EC2::Route'
    Properties:
      GatewayId: !Ref MyIGW
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRT
  DMZ1toPublicRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT     # required
      SubnetId: !Ref DMZ1    # required
  DMZ2toPublicRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT     # required
      SubnetId: !Ref DMZ2    # required
  PRV1toPrivateRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRT     # required
      SubnetId: !Ref PRV1    # required
  PRV2toPrivateRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRT     # required
      SubnetId: !Ref PRV2    # required
